fc_linear_regression:
  files:
    input: "client1.csv"
    sep: ","
    label_column: "label"

  evaluation:
    test_size: 0.33 # if None, no evaluation will be performed
    random_state: 42 # For reproducibility, also None possible
